controllers:
    resource:
        path: '../Controller/'
        namespace: IncCom\Controller
    type: attribute

inccom_token_refresh:
    path: /api/IncCom/token/refresh
    methods: [POST]
    controller: gesdinet.jwtrefreshtoken::refresh
