security:
    firewalls:
        schooltask_login:
            pattern: ^/api/schooltask/auth/login$
            stateless: true
            provider: email_user_provider
            user_checker: app.security.schooltask_login_user_checker
            json_login:
                check_path: /api/schooltask/auth/login
                username_path: username
                password_path: password
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        schooltask_refresh:
            pattern: ^/api/schooltask/token/refresh
            stateless: true
            provider: login_user_provider
            user_checker: App\Security\UserChecker
            refresh_jwt:
                check_path: /api/schooltask/token/refresh

    access_control:
        - { path: ^/api/schooltask/auth/login$, roles: PUBLIC_ACCESS, methods: [POST, GET] }
        - { path: ^/api/schooltask/auth/logout$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/schooltask/token/refresh$, roles: PUBLIC_ACCESS, methods: [POST] }
