import type { ListRequest, SettingCategory } from '@/types/api.types';

export const queryKeys = {
	auth: {
		user: ['auth', 'user'] as const,
		check: ['auth', 'check'] as const,
	},
	account: {
		detail: ['account', 'detail'] as const,
		map: ['account', 'map'] as const,
		accesses: ['account', 'accesses'] as const,
		roles: ['account', 'roles'] as const,
		options: ['account', 'options'] as const,
	},
	settings: {
		all: (category?: SettingCategory) => ['settings', category ?? 'all'] as const,
		one: (category: SettingCategory, key: string) => ['settings', category, key] as const,
	},
	main: {
		users: (filters: ListRequest) => ['main', 'users', filters] as const,
		user: (id: number) => ['main', 'user', id] as const,
		userFilter: ['main', 'user', 'filter'] as const,
		userSelect: (filters?: ListRequest['filters']) => ['main', 'user', 'select', filters] as const,
		userRoleOptions: ['main', 'user', 'role-options'] as const,
		groups: (filters: ListRequest) => ['main', 'groups', filters] as const,
		group: (id: number) => ['main', 'group', id] as const,
		groupFilter: ['main', 'group', 'filter'] as const,
		ous: (filters: ListRequest) => ['main', 'ous', filters] as const,
		ou: (id: number) => ['main', 'ou', id] as const,
		claimants: (filters: ListRequest) => ['main', 'claimants', filters] as const,
		claimant: (id: number) => ['main', 'claimant', id] as const,
	},
	device: {
		list: (filters: ListRequest) => ['device', 'list', filters] as const,
		detail: (id: number) => ['device', 'detail', id] as const,
		filter: ['device', 'filter'] as const,
		devices: (filters: ListRequest) => ['device', 'devices', filters] as const,
		device: (id: number) => ['device', 'device', id] as const,
		subDevices: (filters: ListRequest) => ['device', 'subDevices', filters] as const,
		subDevice: (id: number) => ['device', 'subDevice', id] as const,
		types: (filters: ListRequest) => ['device', 'types', filters] as const,
		type: (id: number) => ['device', 'type', id] as const,
		properties: (filters: ListRequest) => ['device', 'properties', filters] as const,
		property: (id: number) => ['device', 'property', id] as const,
		components: (filters: ListRequest) => ['device', 'components', filters] as const,
		component: (id: number) => ['device', 'component', id] as const,
		software: (filters: ListRequest) => ['device', 'software', filters] as const,
		softwareDetail: (id: number) => ['device', 'software', 'detail', id] as const,
		softwareTypes: (filters: ListRequest) => ['device', 'softwareTypes', filters] as const,
		softwareType: (id: number) => ['device', 'softwareType', id] as const,
		licenses: (filters: ListRequest) => ['device', 'licenses', filters] as const,
		license: (id: number) => ['device', 'license', id] as const,
		licenseKeys: (filters: ListRequest) => ['device', 'licenseKeys', filters] as const,
		licenseKey: (id: number) => ['device', 'licenseKey', id] as const,
	},
} as const;
