controllers:
  resource:
    path: '../Controller/'
    namespace: SchoolTask\Controller
  type: attribute

schooltask_token_refresh:
  path: /api/schooltask/token/refresh
  methods: [POST]
  controller: gesdinet.jwtrefreshtoken::refresh
